x-microservice-base: &microservice-base
  env_file: .env.encrypted
  environment: &microservice-base-env
    AUTH_WSHOST: ws://auth-service:5001/rpc
    CACHE_WSHOST: ws://cache-service:5002/rpc
    UTILITY_WSHOST: ws://utility-service:5003/rpc
    CORE_WSHOST: ws://core-service:5004/rpc
  depends_on:
    mongodb:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "500k"
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: "512M"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: |
        mongosh --quiet --eval "
        try { 
          rs.status(); 
        } catch(e) { 
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongodb:27017' }]
          });
        }"
      interval: 5s
      timeout: 10s
      retries: 5

  gateway-service:
    image: nginx:alpine
    container_name: gateway-service
    ports:
      - "3000:80"
    volumes:
      - ./microservice/gateway-service/include.d:/etc/nginx/include.d:ro
      - ./microservice/gateway-service/proxy_settings.conf:/etc/nginx/proxy_settings.conf:ro
      - ./microservice/gateway-service/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./microservice/frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - auth-service
      - utility-service
      
  auth-service:
    build:
      context: .
      dockerfile: microservice/auth-service/Dockerfile
    container_name: auth-service
    <<: *microservice-base
    environment:
      <<: *microservice-base-env
      PORT: 5001

  cache-service:
    build:
      context: .  # Build from root
      dockerfile: microservice/cache-service/Dockerfile
    container_name: cache-service
    <<: *microservice-base
    environment:
      <<: *microservice-base-env
      PORT: 5002
  utility-service:
    build:
      context: .  # Build from root
      dockerfile: microservice/utility-service/Dockerfile
    container_name: utility-service
    <<: *microservice-base
    environment:
      <<: *microservice-base-env
      PORT: 5003
  core-service:
    build:
      context: .
      dockerfile: microservice/core-service/Dockerfile
    container_name: core-service
    <<: *microservice-base
    environment:
      <<: *microservice-base-env
      PORT: 5004

volumes:
  mongo-data:
  rabbitmq-data:

networks:
  default:
    driver: bridge
